name: Job Outputs Demo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      build_date: ${{ steps.date.outputs.today }}

    steps:
      - name: Generate Today's Date
        id: date
        run: |
          echo "today=$(date +%F)" >> $GITHUB_OUTPUT

  display:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Print Job Output
        run: |
          echo "Today's date is: ${{ needs.build.outputs.build_date }}"