name: scheduled-run

on:
  schedule: 
    - cron: '0 0 * * *'

jobs:
  scheduled-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: message
        run: |
          echo "This is an automatic trigger to check dependecy if any"
